# Generated by ChatGPT

import random

def check_string(n, s):
    ok = True
    curr = (s[0] == '1')
    cnt = 0

    for i in range(n):
        if s[i] == '0':
            cnt += 1
        if i == 0:
            continue
        if s[i] == s[i - 1] and s[i] == '0':
            curr = False
        if s[i] == s[i - 1] and s[i] == '1':
            if curr and cnt % 2 == 1:
                ok = False
            curr = True
            cnt = 0

    if curr and cnt % 2 == 1 and s[n - 1] == '1':
        ok = False

    return "YES" if ok else "NO"


def generate_test_cases(filename="cases.txt", T=10000, max_n=10000):
    answers = []
    with open(filename, "w") as f:
        f.write(str(T) + "\n")

        for _ in range(T):
            n = random.randint(1, max_n)
            s = ''.join(random.choice('01') for _ in range(n))
            f.write(str(n) + "\n")
            f.write(s + "\n")
            answers.append(check_string(n, s))
    
    with open("output.txt", "w") as f2:
        for ans in answers:
            f2.write(ans + "\n")

    print(f"Test cases written to {filename}")


if __name__ == "__main__":
    generate_test_cases()
